### ISSUE TITLE
Delete default route from main on SIGTERM

### ISSUE THREAD

**Issue by genofire** [freifunk-gluon/l3roamd#56]
The routing entry at table main disapear:
`default via 2a02:16d0:1003:700::1 dev ens3`

state before SIGTERM:
```sh
 echo "get_prefixes" | socat - unix:/var/run/l3roamd.sock
{ "prefixes": [ "::ffff:0.0.0.0", "2a06:8782:ffbb:bab1::", "fe80::" ] }
```

----
I am little bit confused, maybe this is the solution:

Why is he deleting from 254 and not from given `l3ctx.clientmgr_ctx.export_table`
https://github.com/freifunk-gluon/l3roamd/blob/3c7b4447aece012093a7e50653835cca4e48c953/src/main.c#L67

**Comment by christf** [comment]
On Sat, Nov 24, 2018 at 07:25:07AM -0800, Geno wrote:
>
>
>I am little bit confused, maybe this is the solution:
>
>Why is he deleting from 254 and not from given `l3ctx.clientmgr_ctx.export_table`
>https://github.com/freifunk-gluon/l3roamd/blob/3c7b4447aece012093a7e50653835cca4e48c953/src/main.c#L67

L3roamd writes to the main routing table when new prefixes are added 
because those prefixes should be made available.

I agree, when specifying -t then only this table should be used.


-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Comment by christf** [comment]
there is more to it:

* the routes of the client prefix are removed from the main routing table because they are added there when initializing the routemanager
* the route you are describing is not for one of the client prefixes but a default route.  This is a bug.
